[package]
name = "keiro"
version = "0.1.0"
edition = "2021"

[dependencies]
itertools = "*"
geo = "*"
proptest = "*"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "*"
petgraph = "*"
