[package]
name = "keiro"
version = "0.1.0"
edition = "2021"

[dependencies]
itertools = "0.13.0"
geo = "0.28.0"
proptest = "1.5.0"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
petgraph = "0.6.5"
